import { useState } from 'react'
import { useRouter } from 'next/router'
import { useUserContext } from 'context/UserContext'
import { IoMdClose } from 'react-icons/io'
import { FiDownload, FiCheckCircle, FiLock, FiFileText } from 'react-icons/fi'

export default function OfferLetter() {
	const { isLoggedIn, user } = useUserContext()
	const router = useRouter()
	const [showDocModal, setShowDocModal] = useState(false)

	const currentPoints = Number(user?.points || 0)
	const isEligible = Boolean(isLoggedIn && currentPoints >= 299)
	const remaining = Math.max(0, 299 - currentPoints)

	const handleDownload = () => {
		window.print()
	}

	const today = new Date().toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric',
	})

	const ambassadorName = user?.name || 'Authorized Campus Ambassador'
	const collegeName = user?.college || 'Affiliated Institution'
	const ambassadorId = user?.tathvaId || user?.userId ? `TCA26-${user?.tathvaId || user?.userId}` : 'TCA26-PENDING'

	return (
		<section className='offer-letter-section' id='offer-letter'>
			<div className='container'>
				<div className='offer-header'>
					<span className='offer-overline'>07 // MILESTONE CERTIFICATION</span>
					<h2 className='offer-title'>
						The 299-Point <span className='text-gradient-gold'>Offer Letter</span>.
					</h2>
					<p className='offer-subtitle'>
						Achieving 299 points validates your status as an official qualified Campus Ambassador for
						Tathva &apos;26, unlocking formal certification endorsed by National Institute of Technology
						Calicut.
					</p>
				</div>

				{/* Milestone Stage Card */}
				<div className={`offer-stage-card ${isEligible ? 'stage-unlocked' : 'stage-locked'}`}>
					<div className='offer-stage-content'>
						{/* Left: Information & Status */}
						<div className='offer-info-col'>
							<div className={`milestone-badge ${isEligible ? 'badge-unlocked' : 'badge-locked'}`}>
								{isEligible ? (
									<>
										<FiCheckCircle />
										<span>MILESTONE UNLOCKED // 299 PTS CROSS</span>
									</>
								) : (
									<>
										<FiLock />
										<span>MILESTONE LOCKED // 299 PTS REQUIRED</span>
									</>
								)}
							</div>

							<h3 className='offer-stage-heading'>
								{isEligible ? (
									<>
										Offer Letter <span className='text-gradient-gold'>Unlocked</span>
									</>
								) : (
									'Official Offer Letter'
								)}
							</h3>

							<p className='offer-stage-text'>
								{isEligible
									? "You've successfully crossed the 299-point milestone. Your official Tathva '26 Campus Ambassador Offer Letter has been verified and generated by NIT Calicut."
									: `Reach 299 points to unlock your official Tathva '26 Campus Ambassador Offer Letter. ${
											isLoggedIn
												? `You are currently at ${currentPoints} points (${remaining} points remaining).`
												: 'Sign in to review your current points and progress.'
									  }`}
							</p>

							{/* Actions depending on eligibility */}
							<div className='offer-actions-row'>
								{isEligible ? (
									<>
										<button onClick={() => setShowDocModal(true)} className='btn-primary'>
											<FiFileText />
											<span>View Offer Letter</span>
										</button>
										<button onClick={handleDownload} className='btn-outline'>
											<FiDownload />
											<span>Download / Print</span>
										</button>
									</>
								) : (
									<a href='#points' className='btn-outline'>
										<span>View Progress</span>
										<span>↑</span>
									</a>
								)}
							</div>
						</div>

						{/* Right: Document Preview Silhouette */}
						<div className='offer-preview-col'>
							<div className='offer-doc-mockup'>
								<div className='mockup-header'>
									<img
										src='/images/tathva26-gold.png'
										alt="Tathva '26"
										style={{ height: 26, width: 'auto' }}
									/>
									<span className='mockup-seal'>NIT CALICUT // &apos;26</span>
								</div>

								<div className='mockup-lines'>
									<div className='mock-line' style={{ width: '85%' }}></div>
									<div className='mock-line' style={{ width: '100%' }}></div>
									<div className='mock-line' style={{ width: '65%' }}></div>
								</div>

								<div className='mockup-meta-pill'>
									<span>STATUS: {isEligible ? 'QUALIFIED' : 'IN PROGRESS'}</span>
									<span style={{ color: isEligible ? '#10B981' : '#FFB347' }}>
										{isEligible ? '299+ PTS ✓' : `${currentPoints}/299 PTS`}
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			{/* High-Fidelity Official Document Modal */}
			{showDocModal && (
				<div className='doc-modal-overlay' onClick={() => setShowDocModal(false)}>
					<div className='doc-modal-container' onClick={(e) => e.stopPropagation()}>
						<button
							className='modal-close-btn'
							onClick={() => setShowDocModal(false)}
							aria-label='Close Offer Letter'
						>
							<IoMdClose />
						</button>

						{/* Official Printable Document */}
						<div className='official-letter-paper' id='printable-offer-letter'>
							<div className='letter-header'>
								<img
									src='/images/tathva26-gold.png'
									alt="Tathva '26"
									className='letter-logo'
								/>
								<div className='letter-header-meta'>
									<div>TATHVA &apos;26</div>
									<div>NATIONAL INSTITUTE OF TECHNOLOGY CALICUT</div>
									<div>CAMPUS AMBASSADOR NETWORK</div>
								</div>
							</div>

							<div className='letter-title-block'>
								<span className='letter-supertitle'>OFFICIAL CONFIRMATION</span>
								<h2 className='letter-main-title'>OFFER LETTER</h2>
							</div>

							<p className='letter-body-text'>
								This is to certify and confirm that
								<span className='letter-highlight-name'>{ambassadorName}</span>
								from
								<span className='letter-highlight-name' style={{ color: '#ffffff', fontSize: '1.15rem' }}>
									{collegeName}
								</span>
								has successfully qualified for the <strong>Tathva &apos;26 Campus Ambassador Program</strong> by
								achieving the required milestone of <strong>299 points</strong> through active engagement,
								outreach coordination, and technical festival promotion.
							</p>

							{/* Verified Credentials Block */}
							<div className='letter-credentials-grid'>
								<div className='cred-item'>
									<span className='cred-label'>Ambassador ID</span>
									<span className='cred-val'>{ambassadorId}</span>
								</div>
								<div className='cred-item'>
									<span className='cred-label'>Verified Points</span>
									<span className='cred-val text-gradient-gold'>{currentPoints} PTS</span>
								</div>
								<div className='cred-item'>
									<span className='cred-label'>Issue Date</span>
									<span className='cred-val'>{today}</span>
								</div>
							</div>

							<div className='letter-footer'>
								<div className='letter-issuing-authority'>
									<strong>Tathva &apos;26 Executive Committee</strong>
									<br />
									National Institute of Technology Calicut
									<br />
									Kozhikode, Kerala — 673601
								</div>
								<div style={{ textAlign: 'right' }}>
									<span className='section-label' style={{ fontSize: '0.7rem' }}>
										OFFICIAL CREDENTIAL
									</span>
								</div>
							</div>
						</div>

						{/* Modal Actions */}
						<div className='modal-actions-bar'>
							<button onClick={handleDownload} className='btn-primary'>
								<FiDownload />
								<span>Download / Print Official Document</span>
							</button>
							<button onClick={() => setShowDocModal(false)} className='btn-secondary'>
								Close
							</button>
						</div>
					</div>
				</div>
			)}
		</section>
	)
}
