import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import { toast } from 'react-toastify'
import { useUserContext } from 'context/UserContext'
import axios from 'axios'
import { FiDownload, FiFileText, FiCheckCircle, FiLock } from 'react-icons/fi'
import OfferLetterModal from 'components/common/OfferLetterModal'

import styles from '../../styles/profile.module.css'

export default function ProfilePage() {
	const { user, accessToken, logout } = useUserContext()
	const router = useRouter()
	const [form, setForm] = useState(null)
	const [loading, setLoading] = useState(true)
	const [showOfferModal, setShowOfferModal] = useState(false)

	useEffect(() => {
		if (!user || !accessToken) {
			router.push('/login')
			return
		}
		fetchProfile()
	}, [accessToken, user])

	const fetchProfile = async () => {
		try {
			const { data } = await axios.get(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/user/`, {
				headers: {
					Authorization: `Bearer ${accessToken}`,
				},
			})
			setForm(data)
			setLoading(false)
		} catch (err) {
			console.error(err)
			toast.error('Failed to load profile')
			setLoading(false)
		}
	}

	if (loading) {
		return (
			<div className='container'>
				<div className={styles['profile-loading']}>Loading profile...</div>
			</div>
		)
	}

	const totalPoints = Number(form?.totalPoints ?? form?.points ?? user?.points ?? 0)
	const isEligible = totalPoints >= 299
	const remainingPoints = Math.max(0, 299 - totalPoints)
	const progressPercent = Math.min(100, Math.round((totalPoints / 299) * 100))

	const combinedUserData = {
		name: form?.name || user?.name,
		email: form?.email || user?.email,
		college: form?.college || user?.college,
		tathvaId: form?.tathvaId || form?.tathva_id || user?.tathvaId || user?.userId,
		points: totalPoints,
		is_ca: form?.is_ca || user?.is_ca,
	}

	const handleDownloadOfferLetter = () => {
		setShowOfferModal(true)
		setTimeout(() => {
			window.print()
		}, 300)
	}

	return (
		<div className='container'>
			<div className={styles['profile-wrapper']}>
				<div className={styles['profile-header']}>
					<div className={styles['profile-header-info']}>
						<h1 className={styles['profile-name']}>{form?.name}</h1>
						<p className={styles['profile-email']}>{form?.email}</p>
						{form?.tathvaId && <p className={styles['profile-id']}>Tathva ID: {form.tathvaId}</p>}
						{form?.is_ca && <span className={styles['profile-ca-badge']}>Campus Ambassador</span>}
					</div>
				</div>

				{/* Offer Letter Milestone Card */}
				<div className={`${styles['profile-offer-card']} ${isEligible ? styles['offer-card-unlocked'] : ''}`}>
					<div className={styles['offer-card-badge-row']}>
						<span className={isEligible ? styles['badge-unlocked'] : styles['badge-locked']}>
							{isEligible ? (
								<>
									<FiCheckCircle />
									<span>Unlocked · 299+ points</span>
								</>
							) : (
								<>
									<FiLock />
									<span>Locked · {totalPoints}/299 points</span>
								</>
							)}
						</span>
						<span className={styles['offer-edition-tag']}>Official Tathva &apos;26 credential</span>
					</div>

					<div className={styles['offer-card-main']}>
						<div className={styles['offer-card-info']}>
							<h2 className={styles['offer-card-title']}>
								Campus Ambassador <span className='text-gradient-gold'>Offer Letter</span>
							</h2>
							<p className={styles['offer-card-desc']}>
								{isEligible
									? "Your official Tathva '26 Campus Ambassador Appointment Letter has been verified and generated by NIT Calicut. You can download or print your official credential below."
									: `Accumulate 299 milestone points to automatically unlock your official Tathva '26 Offer Letter endorsed by NIT Calicut. You are currently at ${totalPoints} points (${remainingPoints} points remaining).`}
							</p>

							<div className={styles['offer-progress-wrap']}>
								<div className={styles['offer-progress-bar']}>
									<div
										className={styles['offer-progress-fill']}
										style={{ width: `${progressPercent}%` }}
									/>
								</div>
								<span className={styles['offer-progress-text']}>
									{totalPoints} / 299 PTS ({progressPercent}%)
								</span>
							</div>
						</div>

						<div className={styles['offer-card-actions']}>
							{isEligible ? (
								<>
									<button onClick={handleDownloadOfferLetter} className='btn-primary'>
										<FiDownload />
										<span>Download / Print PDF</span>
									</button>
									<button onClick={() => setShowOfferModal(true)} className='btn-outline'>
										<FiFileText />
										<span>View Offer Letter</span>
									</button>
								</>
							) : (
								<button onClick={() => setShowOfferModal(true)} className='btn-secondary'>
									<FiFileText />
									<span>Preview Offer Letter Template</span>
								</button>
							)}
						</div>
					</div>
				</div>

				<div className={styles['profile-details']}>
					<div className={styles['profile-section']}>
						<h2 className={styles['profile-section-title']}>Personal Information</h2>
						<div className={styles['profile-info-grid']}>
							<div className={styles['profile-info-item']}>
								<span className={styles['profile-info-label']}>Name</span>
								<span className={styles['profile-info-value']}>
									{form?.name || 'Not provided'}
								</span>
							</div>
							<div className={styles['profile-info-item']}>
								<span className={styles['profile-info-label']}>Email</span>
								<span className={styles['profile-info-value']}>
									{form?.email || 'Not provided'}
								</span>
							</div>
							<div className={styles['profile-info-item']}>
								<span className={styles['profile-info-label']}>Phone</span>
								<span className={styles['profile-info-value']}>
									{form?.phone || 'Not provided'}
								</span>
							</div>
						</div>
					</div>

					<div className={styles['profile-section']}>
						<h2 className={styles['profile-section-title']}>Academic Information</h2>
						<div className={styles['profile-info-grid']}>
							<div className={styles['profile-info-item']}>
								<span className={styles['profile-info-label']}>Institute</span>
								<span className={styles['profile-info-value']}>
									{form?.college || 'Not provided'}
								</span>
							</div>
							<div className={styles['profile-info-item']}>
								<span className={styles['profile-info-label']}>Branch</span>
								<span className={styles['profile-info-value']}>
									{form?.branch || 'Not provided'}
								</span>
							</div>
							<div className={styles['profile-info-item']}>
								<span className={styles['profile-info-label']}>Year of Study</span>
								<span className={styles['profile-info-value']}>
									{form?.year || 'Not provided'}
								</span>
							</div>
							<div className={styles['profile-info-item']}>
								<span className={styles['profile-info-label']}>Previous CA Experience</span>
								<span className={styles['profile-info-value']}>
									{form?.experience ? 'Yes' : 'No'}
								</span>
							</div>
						</div>
					</div>

					<div className={styles['profile-actions']}>
						<button className='btn-secondary' onClick={logout}>
							Logout
						</button>
					</div>
				</div>
			</div>

			<OfferLetterModal
				isOpen={showOfferModal}
				onClose={() => setShowOfferModal(false)}
				customUser={combinedUserData}
			/>

			<div className='spacerv-md'></div>
		</div>
	)
}